"""initial schema: providers, source_mappings, competitions, seasons,
teams, fixtures, odds_quotes, stats_snapshots

Hand-authored (not autogenerated) so it can be reviewed and committed
without a live Postgres connection available — see the note in
DEVELOPMENT.md's definition of done about migrations shipping with the code
that needs them. Mirrors backend/models/{base,providers,fixtures,odds,stats}.py
exactly; if the two ever diverge, the ORM models are the bug.

Revision ID: 7fea98ca999e
Revises:
Create Date: 2026-09-06 10:46:52.994391

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fea98ca999e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- providers ---
    op.create_table(
        "providers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("kind", sa.String(60), nullable=False),
        sa.Column("base_url", sa.String(255)),
        sa.Column("is_active", sa.Boolean, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("name", name="uq_providers_name"),
    )

    # --- competitions / seasons / teams ---
    op.create_table(
        "competitions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("country", sa.String(80)),
        sa.Column("tier", sa.Integer),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "seasons",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "competition_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("competitions.id"),
            nullable=False,
        ),
        sa.Column("label", sa.String(20), nullable=False),
        sa.Column("start_date", sa.Date),
        sa.Column("end_date", sa.Date),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "competition_id", "label", name="uq_season_competition_label"
        ),
    )
    op.create_index("ix_seasons_competition_id", "seasons", ["competition_id"])

    op.create_table(
        "teams",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("short_name", sa.String(40)),
        sa.Column("country", sa.String(80)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    # --- source_mappings (depends on providers) ---
    # Note: passing this ENUM to create_table() below is sufficient — it
    # emits CREATE TYPE itself via a before_create hook. Calling .create()
    # here too would try to create it twice.
    entity_type_enum = postgresql.ENUM(
        "fixture", "team", "competition", "season", name="entity_type"
    )

    op.create_table(
        "source_mappings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "provider_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("providers.id"),
            nullable=False,
        ),
        sa.Column("entity_type", entity_type_enum, nullable=False),
        sa.Column("external_id", sa.String(120), nullable=False),
        sa.Column("canonical_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "provider_id", "entity_type", "external_id", name="uq_source_mapping"
        ),
    )
    op.create_index("ix_source_mappings_provider_id", "source_mappings", ["provider_id"])
    op.create_index("ix_source_mappings_canonical_id", "source_mappings", ["canonical_id"])

    # --- fixtures (depends on competitions, seasons, teams) ---
    fixture_status_enum = postgresql.ENUM(
        "scheduled", "live", "finished", "postponed", "cancelled", name="fixture_status"
    )

    op.create_table(
        "fixtures",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "competition_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("competitions.id"),
            nullable=False,
        ),
        sa.Column(
            "season_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("seasons.id"),
            nullable=False,
        ),
        sa.Column(
            "home_team_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("teams.id"),
            nullable=False,
        ),
        sa.Column(
            "away_team_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("teams.id"),
            nullable=False,
        ),
        sa.Column("kickoff_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", fixture_status_enum, nullable=False),
        sa.Column("venue", sa.String(150)),
        sa.Column("home_goals", sa.Integer),
        sa.Column("away_goals", sa.Integer),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("home_team_id <> away_team_id", name="ck_fixture_distinct_teams"),
    )
    op.create_index("ix_fixtures_competition_id", "fixtures", ["competition_id"])
    op.create_index("ix_fixtures_season_id", "fixtures", ["season_id"])
    op.create_index("ix_fixtures_kickoff_utc", "fixtures", ["kickoff_utc"])

    # --- odds_quotes (depends on fixtures) ---
    op.create_table(
        "odds_quotes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "fixture_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("fixtures.id"),
            nullable=False,
        ),
        sa.Column("bookmaker", sa.String(80), nullable=False),
        sa.Column("market", sa.String(40), nullable=False),
        sa.Column("selection", sa.String(40), nullable=False),
        sa.Column("line", sa.Numeric(6, 2)),
        sa.Column("decimal_odds", sa.Numeric(8, 3), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_odds_quotes_fixture_id", "odds_quotes", ["fixture_id"])
    op.create_index("ix_odds_quotes_bookmaker", "odds_quotes", ["bookmaker"])
    op.create_index("ix_odds_quotes_market", "odds_quotes", ["market"])
    op.create_index("ix_odds_quotes_captured_at", "odds_quotes", ["captured_at"])

    # --- stats_snapshots (depends on teams, fixtures) ---
    stats_subject_type_enum = postgresql.ENUM(
        "team", "fixture", name="stats_subject_type"
    )

    op.create_table(
        "stats_snapshots",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("subject_type", stats_subject_type_enum, nullable=False),
        sa.Column("team_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("teams.id")),
        sa.Column("fixture_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("fixtures.id")),
        sa.Column("as_of_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSON, nullable=False),
        sa.Column("source", sa.String(80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(subject_type = 'team' AND team_id IS NOT NULL AND fixture_id IS NULL) OR "
            "(subject_type = 'fixture' AND fixture_id IS NOT NULL AND team_id IS NULL)",
            name="ck_stats_snapshot_subject",
        ),
    )
    op.create_index("ix_stats_snapshots_team_id", "stats_snapshots", ["team_id"])
    op.create_index("ix_stats_snapshots_fixture_id", "stats_snapshots", ["fixture_id"])
    op.create_index(
        "ix_stats_snapshots_as_of_timestamp", "stats_snapshots", ["as_of_timestamp"]
    )


def downgrade() -> None:
    op.drop_table("stats_snapshots")
    postgresql.ENUM(name="stats_subject_type").drop(op.get_bind(), checkfirst=True)

    op.drop_table("odds_quotes")

    op.drop_table("fixtures")
    postgresql.ENUM(name="fixture_status").drop(op.get_bind(), checkfirst=True)

    op.drop_table("source_mappings")
    postgresql.ENUM(name="entity_type").drop(op.get_bind(), checkfirst=True)

    op.drop_table("teams")
    op.drop_table("seasons")
    op.drop_table("competitions")
    op.drop_table("providers")
