"""phase 2: model_registry, model_runs, predictions, audit_events

Hand-authored (not autogenerated), matching the Phase 1 migration's
convention — mirrors backend/models/{registry,predictions,audit}.py exactly;
if the two ever diverge, the ORM models are the bug. See DEVELOPMENT.md's
definition of done on migrations shipping with the code that needs them.

Note on Postgres ENUMs: passing an ENUM to create_table() is sufficient — it
emits CREATE TYPE via a before_create hook, so we must NOT also call
.create() on it (that double-creates). Each ENUM is dropped explicitly in
downgrade() after its table.

Revision ID: e461c24386f2
Revises: 7fea98ca999e
Create Date: 2026-09-06 11:10:16.201222

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e461c24386f2'
down_revision: str | Sequence[str] | None = '7fea98ca999e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- model_registry ---
    model_family_enum = postgresql.ENUM(
        "poisson", "dixon_coles", "zinb", "elo", "bayesian_hierarchical",
        "market", "ensemble", name="model_family",
    )
    model_status_enum = postgresql.ENUM(
        "development", "challenger", "champion", "retired", name="model_status",
    )

    op.create_table(
        "model_registry",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("family", model_family_enum, nullable=False),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("version", sa.String(40), nullable=False),
        sa.Column("status", model_status_enum, nullable=False),
        sa.Column("training_window_start", sa.DateTime(timezone=True)),
        sa.Column("training_window_end", sa.DateTime(timezone=True)),
        sa.Column("code_commit", sa.String(64)),
        sa.Column("artefact_hash", sa.String(128)),
        sa.Column("artefact_uri", sa.String(255)),
        sa.Column("hyperparameters", postgresql.JSON),
        sa.Column("description", sa.String(500)),
        sa.Column("promoted_at", sa.DateTime(timezone=True)),
        sa.Column("retired_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("name", "version", name="uq_model_registry_name_version"),
    )
    op.create_index("ix_model_registry_family", "model_registry", ["family"])
    op.create_index("ix_model_registry_status", "model_registry", ["status"])

    # --- model_runs (depends on model_registry) ---
    model_run_kind_enum = postgresql.ENUM(
        "training", "backtest", "inference", "evaluation", name="model_run_kind",
    )
    model_run_status_enum = postgresql.ENUM(
        "running", "succeeded", "failed", name="model_run_status",
    )

    op.create_table(
        "model_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "model_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("model_registry.id"), nullable=False,
        ),
        sa.Column("kind", model_run_kind_enum, nullable=False),
        sa.Column("status", model_run_status_enum, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("data_as_of", sa.DateTime(timezone=True)),
        sa.Column("data_snapshot_ref", sa.String(128)),
        sa.Column("code_commit", sa.String(64)),
        sa.Column("parameters", postgresql.JSON),
        sa.Column("metrics", postgresql.JSON),
        sa.Column("log_uri", sa.String(255)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_model_runs_model_id", "model_runs", ["model_id"])
    op.create_index("ix_model_runs_kind", "model_runs", ["kind"])
    op.create_index("ix_model_runs_data_as_of", "model_runs", ["data_as_of"])

    # --- predictions (depends on fixtures, model_registry) ---
    op.create_table(
        "predictions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "fixture_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("fixtures.id"), nullable=False,
        ),
        sa.Column("prediction_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decision_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("market", sa.String(40), nullable=False),
        sa.Column("selection", sa.String(40), nullable=False),
        sa.Column("line", sa.Numeric(6, 2)),
        sa.Column("model_probabilities", postgresql.JSON),
        sa.Column("ensemble_probability", sa.Numeric(7, 6)),
        sa.Column("calibrated_probability", sa.Numeric(7, 6)),
        sa.Column("conservative_probability", sa.Numeric(7, 6)),
        sa.Column("bookmaker", sa.String(80)),
        sa.Column("executable_odds", sa.Numeric(8, 3)),
        sa.Column("quote_timestamp", sa.DateTime(timezone=True)),
        sa.Column("fair_market_probability", sa.Numeric(7, 6)),
        sa.Column("edge_pp", sa.Numeric(7, 4)),
        sa.Column("expected_value", sa.Numeric(8, 5)),
        sa.Column("uncertainty_measure", sa.Numeric(7, 6)),
        sa.Column("dqs", sa.Numeric(5, 2)),
        sa.Column("qss", sa.Numeric(5, 2)),
        sa.Column("lrs", sa.Numeric(5, 2)),
        sa.Column("mrs", sa.Numeric(5, 2)),
        sa.Column("dynamic_states", postgresql.JSON),
        sa.Column(
            "model_version_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("model_registry.id"),
        ),
        sa.Column("feature_version", sa.String(40)),
        sa.Column("calibration_version", sa.String(40)),
        sa.Column("risk_policy_version", sa.String(40)),
        sa.Column("optimiser_version", sa.String(40)),
        sa.Column("code_commit", sa.String(64)),
        sa.Column("accumulator_id", postgresql.UUID(as_uuid=True)),
        sa.Column("reason_codes", postgresql.JSON),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ensemble_probability IS NULL OR "
            "(ensemble_probability >= 0 AND ensemble_probability <= 1)",
            name="ck_predictions_ensemble_probability_unit_interval",
        ),
        sa.CheckConstraint(
            "calibrated_probability IS NULL OR "
            "(calibrated_probability >= 0 AND calibrated_probability <= 1)",
            name="ck_predictions_calibrated_probability_unit_interval",
        ),
        sa.CheckConstraint(
            "conservative_probability IS NULL OR "
            "(conservative_probability >= 0 AND conservative_probability <= 1)",
            name="ck_predictions_conservative_probability_unit_interval",
        ),
        sa.CheckConstraint(
            "fair_market_probability IS NULL OR "
            "(fair_market_probability >= 0 AND fair_market_probability <= 1)",
            name="ck_predictions_fair_market_probability_unit_interval",
        ),
    )
    op.create_index("ix_predictions_fixture_id", "predictions", ["fixture_id"])
    op.create_index(
        "ix_predictions_prediction_timestamp", "predictions", ["prediction_timestamp"]
    )
    op.create_index("ix_predictions_decision_as_of", "predictions", ["decision_as_of"])
    op.create_index("ix_predictions_market", "predictions", ["market"])
    op.create_index("ix_predictions_model_version_id", "predictions", ["model_version_id"])
    op.create_index("ix_predictions_accumulator_id", "predictions", ["accumulator_id"])

    # --- audit_events ---
    audit_event_type_enum = postgresql.ENUM(
        "model_promoted", "model_retired", "policy_change", "config_change",
        "override", "data_revision", "job_failure", "governance", "other",
        name="audit_event_type",
    )
    audit_actor_enum = postgresql.ENUM("system", "human", name="audit_actor")

    op.create_table(
        "audit_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("event_type", audit_event_type_enum, nullable=False),
        sa.Column("actor", audit_actor_enum, nullable=False),
        sa.Column("actor_ref", sa.String(120)),
        sa.Column("action", sa.String(120), nullable=False),
        sa.Column("summary", sa.String(500)),
        sa.Column("entity_type", sa.String(60)),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True)),
        sa.Column("payload", postgresql.JSON),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_audit_events_event_type", "audit_events", ["event_type"])
    op.create_index("ix_audit_events_entity_type", "audit_events", ["entity_type"])
    op.create_index("ix_audit_events_entity_id", "audit_events", ["entity_id"])
    op.create_index("ix_audit_events_occurred_at", "audit_events", ["occurred_at"])


def downgrade() -> None:
    op.drop_table("audit_events")
    postgresql.ENUM(name="audit_actor").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="audit_event_type").drop(op.get_bind(), checkfirst=True)

    op.drop_table("predictions")

    op.drop_table("model_runs")
    postgresql.ENUM(name="model_run_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="model_run_kind").drop(op.get_bind(), checkfirst=True)

    op.drop_table("model_registry")
    postgresql.ENUM(name="model_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="model_family").drop(op.get_bind(), checkfirst=True)
